<?php


function xmldb_clickview_upgrade($oldversion) {
  global $DB;
  $dbman = $DB->get_manager();

  /// Add a new column newcol to the mdl_myqtype_options
  if ($oldversion < 2016052001) {
      // Code to add the column, generated by the 'View PHP Code' option of the XMLDB editor.
      // Define field id to be added to clickview.
      $table = new xmldb_table('clickview');

      $field = new xmldb_field('embedhtml', XMLDB_TYPE_CHAR, '1024', null, XMLDB_NOTNULL, null, '0', 'autoplay');

      // Conditionally launch add field embedhtml.
      if (!$dbman->field_exists($table, $field)) {
          $dbman->add_field($table, $field);
      }

      $field = new xmldb_field('embedlink', XMLDB_TYPE_CHAR, '1024', null, XMLDB_NOTNULL, null, null, 'embedhtml');

      // Conditionally launch add field embedlink.
      if (!$dbman->field_exists($table, $field)) {
          $dbman->add_field($table, $field);
      }

      $field = new xmldb_field('thumbnailurl', XMLDB_TYPE_CHAR, '255', null, XMLDB_NOTNULL, null, null, 'embedlink');

      // Conditionally launch add field thumbnailurl.
      if (!$dbman->field_exists($table, $field)) {
          $dbman->add_field($table, $field);
      }

      $field = new xmldb_field('title', XMLDB_TYPE_CHAR, '255', null, XMLDB_NOTNULL, null, null, 'thumbnailurl');

      // Conditionally launch add field title.
      if (!$dbman->field_exists($table, $field)) {
          $dbman->add_field($table, $field);
      }

      upgrade_mod_savepoint(true, 2016052001, 'clickview');
  }

  return true;
}
